spring:
    datasource:
        url: jdbc:mysql://localhost:3306/helpdesk
        username: root
        password: root
        testWhileIle: true
        validatyonQuery: Select 1
    jpa:
        show-sql: true
        hibernate-ddl-auto: update
        hibernate:
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect


